repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black

- repo: https://github.com/mgedmin/check-manifest
  rev: "0.48"
  hooks:
  - id: check-manifest

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8

# - repo: https://github.com/executablebooks/web-compile
#   rev: v0.2.0
#   hooks:
#     - id: web-compile
#       files: >-
#           (?x)^(
#               tests/example_src/.*|
#               tests/example_dist/.*
#           )$
